### ISSUE TITLE
Strg+c not working

### ISSUE THREAD

**Issue by webernetz** [halon/smtpping#3]
Hi. I am not fully sure if I am doing something wrong, but Strg+c ist not working for directly quitting smtpping. Do you have an idea?

**weberjoh@jw-nb12:~/smtpping$ ./smtpping -c 1 -d -s johannes@webernetz.net johannes@webertest.net**
PING johannes@webertest.net ([80.154.108.237]:25): 93 bytes (SMTP DATA)
^C
^C
^C
^C

Thanks,
Johannes

**Comment by eriklax** [comment]
Thanks, double ctrl+c should now work as expected. https://github.com/halonsecurity/smtpping/commit/7cd36b1ac284245275468207f020fecae4596146
