### ISSUE TITLE
Ability to specify outgoing IP

### ISSUE THREAD

**Issue by Didr** [halon/smtpping#8]
Hey, thanks for the tool. 
The ping command usually has a parameter allowing you to specify an outgoing IP or interface with '-I'.
Is that something that could be implemented into smtpping?

**Comment by eriklax** [comment]
Hi, thanks for the feature request, it just committed a fix https://github.com/halon/smtpping/commit/bbb3138a93c203c06a0c62a0a6c83449222ee0fc

Let me know if its not working
